### ISSUE TITLE
Failed to activate the atom-monokai theme

### ISSUE THREAD

**Issue by anshumanf** [burntime/atom-monokai#9]
[Enter steps to reproduce below:]
1. Install and activate Atom Material UI (https://atom.io/themes/atom-material-ui)
2. Install atom-monokai and attempt to activate

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11
**Thrown From**: [atom-monokai](https://github.com/burntime/atom-monokai) package, v0.10.1
### Stack Trace

Failed to activate the atom-monokai theme

```
At Recursive variable definition for @text-color in /Users/anshumanf/.atom/packages/atom-monokai/index.less:0:8

LessError: Recursive variable definition for @text-color
  at /Users/anshumanf/.atom/packages/atom-monokai/index.less:0:8
```
### Commands

```
     -9:53.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:53 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:29.8.0 pane:split-down (a.link)
     -9:23 pane:close (ul.list-inline.tab-bar.inset-panel)
  2x -8:59.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:57.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -7:30.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -7:29.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -3:47.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:44.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -3:41.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:40.6.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -3:34.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  3x -3:34 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "themes": [
      "atom-material-ui",
      "atom-monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-material-ui, v1.2.8
atom-ternjs, v0.13.2
autoclose-html, v0.23.0
highlight-selected, v0.11.2
linter, v1.11.3
linter-eslint, v7.1.1
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
pigments, v0.24.5
react, v0.14.1

# Dev
No dev packages
```

**Comment by simar7** [comment]
Still reproducible. 😢

**Comment by agodlydeciple** [comment]
any word on a fix for this? I am receiving this as well.

**Comment by burntime** [comment]
Should be fixed now. Please have a look.

**Comment by muendelezaji** [comment]
Still happening in latest release (first-time install).
```
Error compiling Less stylesheet: /Users/user/.atom/packages/atom-monokai/index.less
Line number: 0
Recursive variable definition for @base-background-color

Failed to activate the atom-monokai theme

Recursive variable definition for @base-background-color in /Users/user/.atom/packages/atom-monokai/index.less:0:15
Stack Trace
LessError: Recursive variable definition for @base-background-color
  at /Users/user/.atom/packages/atom-monokai/index.less:0:15

The error was thrown from the atom-monokai package. This issue has already been reported.
```

It appears changing [this line](https://github.com/burntime/atom-monokai/blob/275679121017b14eaa1142c6be6d870ed89a5886/styles/base.less#L6) to `background: darken(@base-background-color, 4%);` and removing the `@syntax-bg` declaration fixes it.
